'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CarfareBatch.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property BulkMailInsert() As String
            Get
                Return ResourceManager.GetString("BulkMailInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  
        '''declare @seq int
        '''
        '''BEGIN TRY
        '''BEGIN tran
        '''
        '''INSERT INTO [T_Carfare] VALUES(
        '''SYSDATETIME()
        ''', &apos;9999&apos;
        ''', SYSDATETIME()
        ''', &apos;9999&apos;
        ''', @WorkerID
        ''', @LastBusinessDayID
        ''', @Year
        ''', @Month
        ''', @Status
        ''', @WriteStatus);
        '''
        '''SELECT @seq = SCOPE_IDENTITY()
        '''
        '''INSERT INTO [S_Session] VALUES(
        '''SYSDATETIME()
        ''', &apos;9999&apos;
        ''', SYSDATETIME()
        ''', &apos;9999&apos;
        ''', @SessionKey
        ''', @seq)
        '''
        '''COMMIT tran
        '''END TRY
        '''
        '''BEGIN CATCH
        '''
        '''    declare @ErrorMessage nvarchar(4000)
        '''    declare @ErrorSeverity int
        '''    declare @ErrorState int
        '''
        '''    SE [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CarfareInsert() As String
            Get
                Return ResourceManager.GetString("CarfareInsert", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
