'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MailSendBatch.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  
        '''declare @MailCount int
        '''declare @CompCount int
        '''
        '''BEGIN TRY
        '''BEGIN tran
        '''
        '''	SELECT @MailCount = CarfareCount FROM S_LastBusinessDay
        '''	WHERE LastBusinessDayID = @LastBusinessDayID
        '''
        '''	SELECT @CompCount = COUNT(*) FROM T_Carfare
        '''	WHERE LastBusinessDayID = @LastBusinessDayID
        '''	 AND Status = @cStatus
        '''
        '''	if @MailCount = @CompCount
        '''	begin
        '''		UPDATE S_LastBusinessDay SET Status = @lStatus
        '''		WHERE LastBusinessDayID = @LastBusinessDayID
        '''	end
        '''
        '''BEGIN CATCH
        '''
        '''    declare @ErrorMessage nvarchar(4000)
        '''    decl [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckLastMail() As String
            Get
                Return ResourceManager.GetString("CheckLastMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [自動送信メール]
        '''
        '''　{0} の{1}月分交通費記載があります。
        '''
        '''　交通費ファイルの確認をお願いします。
        '''
        '''
        '''以上
        '''
        '''-- 
        '''--------------------------------
        '''こちらは自動送信メールとなります。
        '''本メールへ返信はしないでください。
        '''--------------------------------  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MailCompletion_1() As String
            Get
                Return ResourceManager.GetString("MailCompletion_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [自動送信メール]
        '''
        '''　{0} の{1}月分交通費記載はありません。
        '''
        '''
        '''以上
        '''
        '''-- 
        '''--------------------------------
        '''こちらは自動送信メールとなります。
        '''本メールへ返信はしないでください。
        '''--------------------------------  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MailCompletion_2() As String
            Get
                Return ResourceManager.GetString("MailCompletion_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [自動送信メール]
        '''
        ''' 今月の交通費記載をお願いします。
        '''
        ''' *長距離出張の際の飛行機代・新幹線代は記載しないでください
        '''  また、出張先での極地交通費(JR私鉄各線・バス・タクシー利用等)は記載し
        '''  てください
        '''
        '''交通費の記載が完了したら下記URLをクリックしてください。
        '''
        '''　http://{0}:{1}/{2}/success_carfare.aspx?key={3}
        '''
        '''以上
        '''
        '''-- 
        '''-------------------------------------------
        '''こちらは自動送信メールとなります。
        '''本メールへ返信はしないでください。
        '''------------------------------------------- に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MailDescription() As String
            Get
                Return ResourceManager.GetString("MailDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [自動送信メール]
        '''
        ''' 今月の交通費記載をお願いします。
        '''
        ''' *長距離出張の際の飛行機代・新幹線代は記載しないでください
        '''  また、出張先での極地交通費(JR私鉄各線・バス・タクシー利用等)は記載し
        '''  てください
        '''
        '''
        '''以上
        '''
        '''-- 
        '''-------------------------------------------
        '''こちらは自動送信メールとなります。
        '''本メールへ返信はしないでください。
        '''------------------------------------------- に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MailDescriptionAdmin() As String
            Get
                Return ResourceManager.GetString("MailDescriptionAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [自動送信メール]
        '''
        ''' 交通費記載をお願いします。
        '''
        ''' 記載が完了、もしくはすでに記載済みでしたら下記URLをクリックしてください。
        '''
        '''　http://{0}:{1}/{2}/success_carfare.aspx?key={3}
        '''
        '''
        '''以上
        '''
        '''-- 
        '''-------------------------------------------
        '''こちらは自動送信メールとなります。
        '''本メールへ返信はしないでください。
        '''------------------------------------------- に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MailReminder() As String
            Get
                Return ResourceManager.GetString("MailReminder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [自動送信メール]
        '''
        '''　交通費記載が完了していない社員は下記になります。
        '''
        '''{0}
        '''
        '''以上
        '''
        '''-- 
        '''-------------------------------------------
        '''こちらは自動送信メールとなります。
        '''本メールへ返信はしないでください。
        '''------------------------------------------- に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MailReminderReport() As String
            Get
                Return ResourceManager.GetString("MailReminderReport", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
